codecov:
  require_ci_to_pass: no
  bot: steven-zou
  token: 7ec086ae-1431-4be8-af00-b95206144799

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

fixes:
  - "::src/github.com/goharbor/harbor/"
