ARG cgo_enabled
ARG go_os
ARG go_arch

FROM golang:1.19.4

ADD .   /go/src/github.com/aquasecurity/harbor-scanner-trivy/
WORKDIR /go/src/github.com/aquasecurity/harbor-scanner-trivy/

RUN export GOOS=${go_os} GO111MODULE=on CGO_ENABLED=${cgo_enabled} GOARCH=${go_arch} && \
	go build -o scanner-trivy cmd/scanner-trivy/main.go
