FROM golang:1.23.2

ADD .   /go/src/github.com/goharbor/harbor-scanner-trivy/
WORKDIR /go/src/github.com/goharbor/harbor-scanner-trivy/

RUN export GOOS=linux GO111MODULE=on CGO_ENABLED=0 && \
	go build -o scanner-trivy cmd/scanner-trivy/main.go
