FROM photon:2.0

RUN tdnf erase -y toybox && tdnf install -y rpm shadow >> /dev/null \
    && tdnf clean all \
    && groupadd -r -g 10000 scanner \
    && useradd --no-log-init -m -r -g 10000 -u 10000 scanner
