# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 21 
# Issues with these labels will never be considered stale
exemptLabels:
  - backlog
  - kind/debt
  - need-triage
  - kind/requirement
  - king/bug
  - Epic
  - target/1.9.5
  - target/1.10.2
  - target/2.0.0
  - target/2.0.1
  - target/2.1.0
  - candidate/1.9.5
  - candidate/1.10.2
  - candidate/2.0.0
  - candidate/2.0.1
  - candidate/2.1.0
# Label to use when marking an issue as stale
staleLabel: staled
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
