FROM alpine:3.18

RUN apk add --no-cache tzdata shadow  tar gzip sudo cronie rsyslog logrotate \
    && mkdir /var/spool/rsyslog \
    && groupadd -r -g 10000 syslog \
    && useradd --no-log-init -r -g 10000 -u 10000 syslog