#!/bin/sh

# use the explicit state file "/var/lib/logrotate/logrotate.status"
# to avoid permission issues when rotating logs
cd /
/usr/sbin/logrotate -s /var/lib/logrotate/logrotate.status /etc/logrotate.conf
exit 0
