# Use Alpine as the base image
FROM alpine:3.18

# Install tzdata (for time zone data) and shadow (for groupadd and useradd commands)
RUN apk add --no-cache tzdata shadow \
    && groupadd -r -g 10000 harbor \
    && useradd --no-log-init -r -m -g 10000 -u 10000 harbor \
    && mkdir /harbor/
