FROM photon:2.0

RUN tdnf install -y tzdata shadow wget >> /dev/null \
    && tdnf clean all \
    && groupadd -r -g 10000 harbor && useradd --no-log-init -r -m -g 10000 -u 10000 harbor \
    && wget https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/o/openssl11-libs-1.1.1g-2.el7.x86_64.rpm \
    && yum -y install rpm \
    && rpm -ivh openssl11-libs-1.1.1g-2.el7.x86_64.rpm
