{
 "kind": "discovery#restDescription",
 "etag": "\"ye6orv2F-1npMW3u9suM3a7C5Bo/IirqKiawPBlWznB4XZKKLikRaQQ\"",
 "discoveryVersion": "v1",
 "id": "clouddebugger:v2",
 "name": "clouddebugger",
 "version": "v2",
 "revision": "20150725",
 "title": "Google Cloud Debugger API",
 "description": "Lets you examine the stack and variables of your running application without stopping or slowing it down.",
 "ownerDomain": "google.com",
 "ownerName": "Google",
 "documentationLink": "https://cloud.google.com/tools/cloud-debugger",
 "protocol": "rest",
 "baseUrl": "https://clouddebugger.googleapis.com/",
 "basePath": "/",
 "rootUrl": "https://clouddebugger.googleapis.com/",
 "servicePath": "",
 "batchPath": "batch",
 "auth": {
  "oauth2": {
   "scopes": {
    "https://www.googleapis.com/auth/cloud-platform": {
     "description": "View and manage your data across Google Cloud Platform services"
    },
    "https://www.googleapis.com/auth/cloud_debugger": {
     "description": "Manage cloud debugger"
    },
    "https://www.googleapis.com/auth/cloud_debugletcontroller": {
     "description": "Manage active breakpoints in cloud debugger"
    }
   }
  }
 },
 "resources": {
  "controller": {
   "resources": {
    "debuggees": {
     "methods": {
      "register": {
       "id": "clouddebugger.controller.debuggees.register",
       "path": "v2/controller/debuggees/register",
       "httpMethod": "POST",
       "description": "Registers the debuggee with the controller. All agents should call this API with the same request content to get back the same stable 'debuggee_id'. Agents should call this API again whenever ListActiveBreakpoints or UpdateActiveBreakpoint return the error google.rpc.Code.NOT_FOUND. It allows the server to disable the agent or recover from any registration loss. If the debuggee is disabled server, the response will have is_disabled' set to true.",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/cloud_debugletcontroller"
       ]
      }
     },
     "resources": {
      "breakpoints": {
       "methods": {
        "list": {
         "id": "clouddebugger.controller.debuggees.breakpoints.list",
         "path": "v2/controller/debuggees/{debuggeeId}/breakpoints",
         "httpMethod": "GET",
         "description": "Returns the list of all active breakpoints for the specified debuggee. The breakpoint specification (location, condition, and expression fields) is semantically immutable, although the field values may change. For example, an agent may update the location line number to reflect the actual line the breakpoint was set to, but that doesn't change the breakpoint semantics. Thus, an agent does not need to check if a breakpoint has changed when it encounters the same breakpoin[...]",
         "scopes": [
          "https://www.googleapis.com/auth/cloud-platform",
          "https://www.googleapis.com/auth/cloud_debugletcontroller"
         ]
        },
        "update": {
         "id": "clouddebugger.controller.debuggees.breakpoints.update",
         "path": "v2/controller/debuggees/{debuggeeId}/breakpoints/{id}",
         "httpMethod": "PUT",
         "description": "Updates the breakpoint state or mutable fields. The entire Breakpoint protobuf must be sent back to the controller. Updates to active breakpoint fields are only allowed if the new value does not change the breakpoint specification. Updates to the 'location', 'condition' and 'expression' fields should not alter the breakpoint semantics. They are restricted to changes such as canonicalizing a value or snapping the location to the correct line of code.",
         "scopes": [
          "https://www.googleapis.com/auth/cloud-platform",
          "https://www.googleapis.com/auth/cloud_debugletcontroller"
         ]
        }
       }
      }
     }
    }
   }
  },
  "debugger": {
   "resources": {
    "debuggees": {
     "methods": {
      "list": {
       "id": "clouddebugger.debugger.debuggees.list",
       "path": "v2/debugger/debuggees",
       "httpMethod": "GET",
       "description": "Lists all the debuggees that the user can set breakpoints to.",
       "scopes": [
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/cloud_debugger"
       ]
      }
     },
     "resources": {
      "breakpoints": {
       "methods": {
        "set": {
         "id": "clouddebugger.debugger.debuggees.breakpoints.set",
         "path": "v2/debugger/debuggees/{debuggeeId}/breakpoints/set",
         "httpMethod": "POST",
         "description": "Sets the breakpoint to the debuggee.",
         "scopes": [
          "https://www.googleapis.com/auth/cloud-platform",
          "https://www.googleapis.com/auth/cloud_debugger"
         ]
        },
        "get": {
         "id": "clouddebugger.debugger.debuggees.breakpoints.get",
         "path": "v2/debugger/debuggees/{debuggeeId}/breakpoints/{breakpointId}",
         "httpMethod": "GET",
         "description": "Gets breakpoint information.",
         "scopes": [
          "https://www.googleapis.com/auth/cloud-platform",
          "https://www.googleapis.com/auth/cloud_debugger"
         ]
        },
        "delete": {
         "id": "clouddebugger.debugger.debuggees.breakpoints.delete",
         "path": "v2/debugger/debuggees/{debuggeeId}/breakpoints/{breakpointId}",
         "httpMethod": "DELETE",
         "description": "Deletes the breakpoint from the debuggee.",
         "scopes": [
          "https://www.googleapis.com/auth/cloud-platform",
          "https://www.googleapis.com/auth/cloud_debugger"
         ]
        },
        "list": {
         "id": "clouddebugger.debugger.debuggees.breakpoints.list",
         "path": "v2/debugger/debuggees/{debuggeeId}/breakpoints",
         "httpMethod": "GET",
         "description": "Lists all breakpoints of the debuggee that the user has access to.",
         "scopes": [
          "https://www.googleapis.com/auth/cloud-platform",
          "https://www.googleapis.com/auth/cloud_debugger"
         ]
        }
       }
      }
     }
    }
   }
  }
 }
}
