// Code generated by mockery v2.1.0. DO NOT EDIT.

package v1

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// responseHandler is an autogenerated mock type for the responseHandler type
type responseHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: code, resp
func (_m *responseHandler) Execute(code int, resp *http.Response) ([]byte, error) {
	ret := _m.Called(code, resp)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(int, *http.Response) []byte); ok {
		r0 = rf(code, resp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *http.Response) error); ok {
		r1 = rf(code, resp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
