// Code generated by mockery v2.53.3. DO NOT EDIT.

package v1

import (
	v1 "github.com/goharbor/harbor/src/pkg/optimizer/rest/v1"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetMetadata provides a mock function with no fields
func (_m *Client) GetMetadata() (*v1.OptimizerAdapterMetadata, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 *v1.OptimizerAdapterMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func() (*v1.OptimizerAdapterMetadata, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *v1.OptimizerAdapterMetadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.OptimizerAdapterMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOptimizationReport provides a mock function with given fields: requestID
func (_m *Client) GetOptimizationReport(requestID string) (string, error) {
	ret := _m.Called(requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetOptimizationReport")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(requestID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(requestID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitOptimize provides a mock function with given fields: req
func (_m *Client) SubmitOptimize(req *v1.OptimizeRequest) (*v1.OptimizeResponse, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for SubmitOptimize")
	}

	var r0 *v1.OptimizeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.OptimizeRequest) (*v1.OptimizeResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*v1.OptimizeRequest) *v1.OptimizeResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.OptimizeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1.OptimizeRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
