// Copyright Project Harbor Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1

import (
	"encoding/json"
	"fmt"
	"slices"

	"github.com/goharbor/harbor/src/lib/errors"
)

// Report statuses reported by the adapter inside the report body. Errors of the
// optimization pipeline (no attestation, LLM failure, ...) are terminal report
// states rather than HTTP errors so that the polling job can always persist an
// outcome.
const (
	// ReportStatusSuccess indicates the optimization finished successfully
	ReportStatusSuccess = "Success"
	// ReportStatusFailed indicates the optimization terminally failed
	ReportStatusFailed = "Failed"

	// ErrorCodeNoAttestation indicates the artifact carries no BuildKit provenance attestation
	ErrorCodeNoAttestation = "NO_ATTESTATION"
	// ErrorCodeExtractionFailed indicates the Dockerfile could not be extracted
	ErrorCodeExtractionFailed = "EXTRACTION_FAILED"
	// ErrorCodeLLMFailed indicates the LLM gateway call failed
	ErrorCodeLLMFailed = "LLM_FAILED"
	// ErrorCodeNoScanReport indicates the artifact has no completed vulnerability
	// scan report, so optimization was not attempted
	ErrorCodeNoScanReport = "NO_SCAN_REPORT"
)

// Optimizer represents metadata of an optimizer adapter which allows Harbor to look up
// an optimizer capable of processing a given artifact stored in its registry and making
// sure that it can interpret the returned result.
type Optimizer struct {
	// The name of the optimizer.
	Name string `json:"name"`
	// The name of the optimizer's provider.
	Vendor string `json:"vendor"`
	// The version of the optimizer.
	Version string `json:"version"`
}

// OptimizerCapability consists of the set of recognized artifact MIME types and the
// set of report MIME types the adapter can produce.
type OptimizerCapability struct {
	// The set of MIME types of the artifacts supported by the optimizer to produce the
	// reports specified in the "produces_mime_types".
	ConsumesMimeTypes []string `json:"consumes_mime_types"`
	// The set of MIME types of reports generated by the optimizer.
	ProducesMimeTypes []string `json:"produces_mime_types"`
}

// OptimizerProperties is a set of custom properties that can further describe
// capabilities of a given optimizer adapter.
type OptimizerProperties map[string]string

// OptimizerAdapterMetadata represents metadata of an optimizer adapter.
type OptimizerAdapterMetadata struct {
	Optimizer    *Optimizer             `json:"optimizer"`
	Capabilities []*OptimizerCapability `json:"capabilities"`
	Properties   OptimizerProperties    `json:"properties"`
}

// Validate validates the metadata
func (md *OptimizerAdapterMetadata) Validate() error {
	if md.Optimizer == nil ||
		len(md.Optimizer.Name) == 0 ||
		len(md.Optimizer.Version) == 0 ||
		len(md.Optimizer.Vendor) == 0 {
		return errors.New("invalid optimizer in metadata")
	}

	if len(md.Capabilities) == 0 {
		return errors.New("invalid capabilities in metadata")
	}

	for _, ca := range md.Capabilities {
		if len(ca.ConsumesMimeTypes) == 0 {
			return errors.New("missing consumes_mime_types in capability")
		}

		if !slices.Contains(ca.ProducesMimeTypes, MimeTypeOptimizationReport) {
			return errors.Errorf("missing %s in produces_mime_types", MimeTypeOptimizationReport)
		}
	}

	return nil
}

// HasCapability returns true when the mime type of the artifact is supported by the optimizer
func (md *OptimizerAdapterMetadata) HasCapability(mimeType string) bool {
	return slices.ContainsFunc(md.Capabilities, func(c *OptimizerCapability) bool {
		return slices.Contains(c.ConsumesMimeTypes, mimeType)
	})
}

// Artifact represents an artifact stored in Registry.
type Artifact struct {
	// The full name of a Harbor repository containing the artifact, including the namespace.
	// For example, `library/oracle/nosql`.
	Repository string `json:"repository"`
	// The info used to identify the version of the artifact.
	Tag string `json:"tag"`
	// The artifact's digest, consisting of an algorithm and hex portion.
	Digest string `json:"digest"`
	// The mime type of the artifact
	MimeType string `json:"mime_type"`
}

// Registry represents Registry connection settings.
type Registry struct {
	// A base URL of the Docker Registry v2 API exposed by Harbor.
	URL string `json:"url"`
	// An optional value of the HTTP Authorization header sent with each request to the
	// Docker Registry for getting or exchanging token.
	// For example, `Basic: Base64(username:password)`.
	Authorization string `json:"authorization"`
	// Insecure is an indicator of https or http.
	Insecure bool `json:"insecure"`
}

// OptimizeRequest represents a structure that is sent to an optimizer adapter to
// initiate the optimization. Conducts all the details required to pull the artifact
// from a Harbor registry.
type OptimizeRequest struct {
	// Connection settings for the Docker Registry v2 API exposed by Harbor.
	Registry *Registry `json:"registry"`
	// Artifact to be optimized.
	Artifact *Artifact `json:"artifact"`
	// ScanReport is the raw vulnerability scan report (JSON) for the artifact, if a
	// completed scan exists. Empty when the artifact has not been scanned; the
	// adapter refuses to optimize in that case rather than guessing.
	ScanReport string `json:"scan_report,omitempty"`
}

// FromJSON parses OptimizeRequest from json data
func (s *OptimizeRequest) FromJSON(jsonData string) error {
	if len(jsonData) == 0 {
		return errors.New("empty json data to parse")
	}

	return json.Unmarshal([]byte(jsonData), s)
}

// ToJSON marshals OptimizeRequest to JSON data
func (s *OptimizeRequest) ToJSON() (string, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return "", err
	}

	return string(data), nil
}

// Validate OptimizeRequest
func (s *OptimizeRequest) Validate() error {
	if s.Registry == nil ||
		len(s.Registry.URL) == 0 {
		return errors.New("optimize request: invalid registry")
	}

	if s.Artifact == nil ||
		len(s.Artifact.Digest) == 0 ||
		len(s.Artifact.Repository) == 0 {
		return errors.New("optimize request: invalid artifact")
	}

	return nil
}

// OptimizeResponse represents the response returned by the optimizer adapter after
// the optimize request is successfully submitted.
type OptimizeResponse struct {
	// e.g: 3fa85f64-5717-4562-b3fc-2c963f66afa6
	ID string `json:"id"`
}

// ReportError carries the terminal failure detail inside an optimization report.
type ReportError struct {
	// Code is one of the ErrorCode* constants
	Code string `json:"code"`
	// Message is the human readable error detail
	Message string `json:"message"`
}

// OptimizationReport is the terminal result document returned by the adapter.
type OptimizationReport struct {
	// Status is ReportStatusSuccess or ReportStatusFailed
	Status string `json:"status"`
	// Error is set when Status is ReportStatusFailed
	Error *ReportError `json:"error,omitempty"`
	// Dockerfile is the original Dockerfile recovered from the provenance attestation
	Dockerfile string `json:"dockerfile,omitempty"`
	// OptimizedDockerfile is the LLM-optimized Dockerfile
	OptimizedDockerfile string `json:"optimized_dockerfile,omitempty"`
	// AttestationManifestDigest is the digest of the attestation manifest
	AttestationManifestDigest string `json:"attestation_manifest_digest,omitempty"`
	// StatementDigest is the digest of the in-toto statement blob
	StatementDigest string `json:"statement_digest,omitempty"`
	// Generated is true when Dockerfile was reconstructed from the image's
	// config history rather than extracted verbatim from a BuildKit
	// provenance attestation (no attestation was found on the artifact).
	Generated bool `json:"generated,omitempty"`
}

// FromJSON parses OptimizationReport from json data
func (r *OptimizationReport) FromJSON(jsonData string) error {
	if len(jsonData) == 0 {
		return errors.New("empty json data to parse")
	}

	return json.Unmarshal([]byte(jsonData), r)
}

// ErrorResponse contains error message when requests are not correctly handled.
type ErrorResponse struct {
	// Error object
	Err *Error `json:"error"`
}

// Error message
type Error struct {
	// Message of the error
	Message string `json:"message"`
}

// Error for ErrorResponse
func (er *ErrorResponse) Error() string {
	if er.Err != nil {
		return er.Err.Message
	}

	return "nil error"
}

// ReportNotReadyError is an error to indicate the optimization report is not ready
type ReportNotReadyError struct {
	// Seconds for next retry
	RetryAfter int
}

// Error for ReportNotReadyError
func (rnr *ReportNotReadyError) Error() string {
	return fmt.Sprintf("report is not ready yet, retry after %d", rnr.RetryAfter)
}
