apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.fullname" . }}-jobservice"
  labels:
{{ include "harbor.labels" . | indent 4 }}
data:
  config.yml: |+
    protocol: "http"
    port: 8080
    worker_pool:
      workers: {{ .Values.jobservice.maxWorkers }}
      backend: "redis"
      redis_pool:
        redis_url: "{{ template "harbor.redisForJobservice" . }}"
        namespace: "harbor_job_service_namespace"
    logger:
      path: "/var/log/jobs"
      level: "INFO"
      archive_period: 14 #days
    admin_server: "http://{{ template "harbor.fullname" . }}-adminserver"
