// Code generated by mockery v2.1.0. DO NOT EDIT.

package cleanup

import (
	context "context"

	model "github.com/goharbor/harbor/src/pkg/systemartifact/model"
	mock "github.com/stretchr/testify/mock"
)

// CleanupCriteria is an autogenerated mock type for the CleanupCriteria type
type CleanupCriteria struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx
func (_m *CleanupCriteria) List(ctx context.Context) ([]*model.SystemArtifact, error) {
	ret := _m.Called(ctx)

	var r0 []*model.SystemArtifact
	if rf, ok := ret.Get(0).(func(context.Context) []*model.SystemArtifact); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.SystemArtifact)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
