FROM demoregistry.dataman-inc.com/library/centos7-base:20160602202509
MAINTAINER zwli zwli@dataman-inc.com

COPY harbor/views /views
COPY harbor/static /static
COPY harbor/CATEGORIES /CATEGORIES
COPY harbor/Deploy/Omega/ui/ /etc/ui
COPY harbor/sql/ /sql
COPY harbor/harbor /

RUN chmod u+x /harbor

ENTRYPOINT ["/harbor"]

#demoregistry.dataman-inc.com/shurenyun/centos7-harbor:tag
