{
 "title": "Harbor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "component up status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "harbor_up", "legendFormat": "{{component}}" }
   ]
  },
  {
   "title": "Quota Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_project_quota_usage_byte",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "project members",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "harbor_project_member_total", "legendFormat": "{{project_name}}" }
   ]
  },
  {
   "title": "Project repo total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "harbor_project_repo_total", "legendFormat": "{{project_name}}" }
   ]
  },
  {
   "title": "artifacts pulled",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "harbor_artifact_pulled", "legendFormat": "{{project_name}}" }
   ]
  },
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "harbor core request rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(harbor_core_http_request_total[5m])",
     "legendFormat": "{{method}} {{operation}}"
    }
   ]
  },
  {
   "title": "API request time 0.9",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "harbor_core_http_request_duration_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{method}} {{operation}}"
    }
   ]
  },
  {
   "title": "harbor core inflight requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "harbor_core_http_inflight_requests",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "General metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Process opened fd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{service=~\"harbor-.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Process CPU time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=~\"harbor-.*\"}[5m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "go threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_threads{service=~\"harbor-.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{service=~\"harbor-.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Go heap objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{service=~\"harbor-.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "go allocated  memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=~\"harbor-.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "go next gc bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{service=~\"harbor-.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "go gc time 0.25",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.25\",service=~\"harbor-.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "go gc time 0.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.5\",service=~\"harbor-.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "go gc time 0.75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.75\",service=~\"harbor-.*\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "JobService Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "task latency",
   "type": "timeseries",
   "description": "time period from last process of task queue",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "harbor_task_queue_latency", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "task concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "harbor_task_concurrency", "legendFormat": "{{type}} pool={{pool}}" }
   ]
  },
  {
   "title": "task queue pending size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "harbor_task_queue_size", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "tasks per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(harbor_task_scheduled_total[1m])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "number of running scheduled jobs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "harbor_task_scheduled_total", "legendFormat": "{{service}}" }
   ]
  },
  { "title": "Registry Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Registry request inflight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "registry_http_in_flight_requests",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Registry request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(registry_http_requests_total[5m])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "registry request time 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(registry_http_request_duration_seconds_bucket[10m]))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "registry request size 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(registry_http_request_size_bytes_bucket[10m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "registry response size 0.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(registry_http_response_size_bytes_bucket[10m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}