FROM photon:2.0

RUN tdnf install -y shadow sudo >>/dev/null\
    && tdnf clean all \
    && mkdir /chartserver/ \
    && mkdir /harbor/ \
    && groupadd -r -g 10000 chartuser \
    && useradd --no-log-init -m -r -g 10000 -u 10000 chartuser