# Use Alpine as the base image
FROM alpine:3.18

# Install nginx and shadow (for groupmod and usermod commands)
RUN apk add --no-cache shadow \
    && groupmod -g 10000 nginx \
    && usermod -g 10000 -u 10000 -d /home/nginx -s /bin/bash nginx \
    && apk add --no-cache nginx \
    && mkdir -p /home/nginx \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log