/* 
 * Harbor API
 *
 * These APIs provide services for manipulating Harbor project.
 *
 * OpenAPI spec version: 0.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package apilib

type AccessLog struct {

	// The ID of the log entry.
	LogId int32 `json:"log_id,omitempty"`

	// Name of the repository in this log entry.
	RepoName string `json:"repo_name,omitempty"`

	// Tag of the repository in this log entry.
	RepoTag string `json:"repo_tag,omitempty"`

	// The operation against the repository in this log entry.
	Operation string `json:"operation,omitempty"`

	// The time when this operation is triggered.
	OpTime string `json:"op_time,omitempty"`
}
