# Use Alpine as the base image
FROM alpine:3.18

# Install shadow (for groupadd and useradd commands) and redis
RUN apk add --no-cache shadow \
    && groupdel ping \
    && groupadd -g 999 redis \
    && useradd -u 999 -g 999 -c "Redis Database Server" -d /var/lib/redis -s /sbin/nologin -m redis \
    && apk add --no-cache redis