// Code generated by mockery v2.1.0. DO NOT EDIT.

package dao

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/goharbor/harbor/src/pkg/immutable/dao/model"

	q "github.com/goharbor/harbor/src/lib/q"
)

// DAO is an autogenerated mock type for the DAO type
type DAO struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx, query
func (_m *DAO) Count(ctx context.Context, query *q.Query) (int64, error) {
	ret := _m.Called(ctx, query)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *q.Query) int64); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *q.Query) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateImmutableRule provides a mock function with given fields: ctx, ir
func (_m *DAO) CreateImmutableRule(ctx context.Context, ir *model.ImmutableRule) (int64, error) {
	ret := _m.Called(ctx, ir)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *model.ImmutableRule) int64); ok {
		r0 = rf(ctx, ir)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *model.ImmutableRule) error); ok {
		r1 = rf(ctx, ir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteImmutableRule provides a mock function with given fields: ctx, id
func (_m *DAO) DeleteImmutableRule(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetImmutableRule provides a mock function with given fields: ctx, id
func (_m *DAO) GetImmutableRule(ctx context.Context, id int64) (*model.ImmutableRule, error) {
	ret := _m.Called(ctx, id)

	var r0 *model.ImmutableRule
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.ImmutableRule); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ImmutableRule)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListImmutableRules provides a mock function with given fields: ctx, query
func (_m *DAO) ListImmutableRules(ctx context.Context, query *q.Query) ([]*model.ImmutableRule, error) {
	ret := _m.Called(ctx, query)

	var r0 []*model.ImmutableRule
	if rf, ok := ret.Get(0).(func(context.Context, *q.Query) []*model.ImmutableRule); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ImmutableRule)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *q.Query) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToggleImmutableRule provides a mock function with given fields: ctx, id, status
func (_m *DAO) ToggleImmutableRule(ctx context.Context, id int64, status bool) error {
	ret := _m.Called(ctx, id, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, bool) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateImmutableRule provides a mock function with given fields: ctx, projectID, ir
func (_m *DAO) UpdateImmutableRule(ctx context.Context, projectID int64, ir *model.ImmutableRule) error {
	ret := _m.Called(ctx, projectID, ir)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *model.ImmutableRule) error); ok {
		r0 = rf(ctx, projectID, ir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
