FROM photon:5.0

RUN tdnf install -y nginx shadow >> /dev/null \
    && tdnf clean all \
    && groupmod -g 10000 nginx && usermod -g 10000 -u 10000 -d /home/nginx -s /bin/bash nginx \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log
