version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - goheader
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - usestdlibvars
    - whitespace
  settings:
    goheader:
      template-path: copyright.tmpl
    dupl:
      threshold: 300
    misspell:
      locale: US,UK
    staticcheck:
      checks:
        - ST1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: "(common/|core/utils/|core/api/|jobservice/api/|registryctl/api/|pkg/permission/types/|pkg/quota/types/|server/middleware/util/|server/registry/util/|pkg/reg/util/)"
      # TODO: Fix package naming - these packages conflict with Go stdlib
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict with Go standard library package names"
        path: "(common/http/|lib/errors/|lib/http/)"
    paths:
      - third_party$
      - builtin$
      - examples$
      - .*_test\.go
      - .*test\.go
      - testing
      - src/jobservice/mgt/mock_manager.go
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
    goimports:
      local-prefixes:
        - github.com/goharbor/harbor
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - .*_test\.go
      - .*test\.go
      - testing
      - src/jobservice/mgt/mock_manager.go
