linters-settings:
  gofmt:
    # Simplify code: gofmt with `-s` option.
    # Default: true
    simplify: false
  misspell:
    locale: US,UK
  goimports:
    local-prefixes: github.com/goharbor/harbor
  stylecheck:
    checks: [
      "ST1019",  # Importing the same package multiple times.
    ]

linters:
  disable-all: true
  enable:
    - gofmt
    - goheader
    - misspell
    - typecheck
    # - dogsled
    # - dupl
    # - depguard
    # - funlen
    # - goconst
    # - gocritic
    # - gocyclo
    # - goimports
    # - goprintffuncname
    - ineffassign
    # - nakedret
    # - nolintlint
    - revive
    - whitespace
    - bodyclose
    - deadcode
    - errcheck
    # - gosec
    - gosimple
    - goimports
    - govet
    # - noctx
    # - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    # - unconvert
    # - unparam
    - unused
    - varcheck
 
run:
  skip-files:
    - ".*_test.go"
    - ".*test.go"
  skip-dirs:
    - "testing"
  timeout: 5m

issue:
  max-same-issues: 0
  max-per-linter: 0

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - goimports
    - path: src/testing/*.go
      linters:
        - goimports
    - path: src/jobservice/mgt/mock_manager.go
      linters:
        - goimports
