#!/bin/bash

set +e

if [ -z $1 ]; then
  error "Please set the 'version' variable"
  exit 1
fi

VERSION="$1"
TARGET_ARCHS="$2"

set -e

# the temp folder to store binary file...
mkdir -p binary
rm -rf binary/registry || true

cd `dirname $0`
cur=$PWD

# the temp folder to store distribution source code...
TEMP=`mktemp -d ${TMPDIR-/tmp}/distribution.XXXXXX`
git clone -b $VERSION https://github.com/distribution/distribution.git $TEMP

# add patch 2879
echo 'add patch https://github.com/distribution/distribution/pull/2879 ...'
cd $TEMP
wget https://github.com/distribution/distribution/pull/2879.patch
git apply 2879.patch

# add patch 3370
echo 'add patch https://github.com/distribution/distribution/pull/3370 ...'
cd $TEMP
wget https://github.com/distribution/distribution/pull/3370.patch
git apply 3370.patch

# add patch redis
git apply $cur/redis.patch
cd $cur

echo 'build the registry binary ...'
cp Dockerfile.binary $TEMP

for targetarch in ${TARGETARCHS}; do
  echo "build the registry $targetarch binary..."
  docker build --build-arg=TARGETARCH=$targetarch -f $TEMP/Dockerfile.binary -t registry-golang-$targetarch $TEMP

  echo "copy the registry $targetarch binary to local..."
  ID=$(docker create registry-golang-$targetarch)
  docker cp $ID:/go/src/github.com/docker/distribution/bin/registry binary/registry-linux-$targetarch


  docker rm -f $ID
  docker rmi -f registry-golang-$targetarch
done

echo "Build registry binary success, then to build photon image..."
cd $cur
cp $TEMP/cmd/registry/config-example.yml config.yml
rm -rf $TEMP
