FROM photon:2.0

# The original script in the docker offical registry image.
RUN tdnf install sudo -y >> /dev/null\
    && tdnf clean all \
    && mkdir /harbor/ \
    && mkdir -p /etc/registry \
    && groupadd -r -g 10000 harbor && useradd --no-log-init -r -g 10000 -u 10000 harbor
