FROM golang:1.13.8

ADD .   /go/src/github.com/quay/clair/
WORKDIR /go/src/github.com/quay/clair/

RUN export CLAIR_VERSION=$(git describe --tag --always --dirty) GO111MODULE=on && \
	go build -ldflags "-X github.com/quay/clair/pkg/version.Version=$CLAIR_VERSION" ./cmd/clair
