name: "Pull Request Checks"
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions: {}

jobs:
  title_check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Conventional commit check
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            chore
            refactor
            revert
            adr
          requireScope: false
          subjectPattern: '^.+$'
